public: true
type: "docs"
category: 
- "collection development and management"
tags:
    - "policy"
title: "Licensing for Archival Description"
description: "License for the use of the Rockefeller Archive Center’s archival description."
pages:
  - ["Licensing for Archival Description", "index"]
