public: False
type: "docs"
category:
tags: Policy

title: archival description licence
description: This document introduces the reader to the "archival description" on the website which is licensed under a Creative Commons Zero (CC0) dedication. It details what the license does and does not cover as well as guidelines for using RAC data.
pages:
  - ["Documentation Title", "index"]
